service: quotinator

provider:
  name: aws
  runtime: java8
  region: us-west-2
  memorySize: 512
  profile: serverless_deploy
  stage: prd
  apiKeys:
    - secret
  iamRoleStatements:
    - Effect: Allow
      Action:
      - s3:GetObject
      Resource:
      - arn:aws:s3:::quotinator-quotes/*

package:
  artifact: build/libs/quotinator-prd-all.jar

functions:
  quotinator:
    handler: com.merricklabs.RandomQuoteHandler
    events:
      - http:
          method: get
          path: quotes/random
          cors: true
          private: true

resources:
  Resources:
    quotesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: quotinator-quotes
        AccessControl: Private